posts/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('posts.views',
    url(r'^$', 'home', name='home'),
    url(r'^new/$', 'new', name='new'),
    url(r'^new/(?P<category_slug>[-\w]+)/$', 'new', name='new'),
    url(r'^(?P<category_slug>[-\w]+)/$', 'category', name='category'),
    url(r'^(?P<category_slug>[-\w]+)/(?P<post_slug>[^/.]*)/$', 'post', name='post'),
    url(r'^(?P<category_slug>[-\w]+)/(?P<post_slug>[^/.]*)/edit/$', 'edit', name='edit'),
    url(r'^(?P<category_slug>[-\w]+)/(?P<post_slug>[^/.]*)/delete/$', 'delete', name='delete'),
    url(r'^(?P<category_slug>[-\w]+)/(?P<post_slug>[^/.]*)/credits/$', 'credits', name='credits'),
    url(r'^(?P<category_slug>[-\w]+)/(?P<post_slug>[^/.]*)/upvote/$', 'upvote', name='upvote'),
    url(r'^(?P<category_slug>[-\w]+)/(?P<post_slug>[^/.]*)/downvote/$', 'downvote', name='downvote'),
    url(r'^(?P<category_slug>[-\w]+)/(?P<post_slug>[^/.]*)/subscribe/$', 'subscribe', name='subscribe'),
    url(r'^(?P<category_slug>[-\w]+)/(?P<post_slug>[^/.]*)/unsubscribe/$', 'unsubscribe', name='unsubscribe'),
)

urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.template.response import TemplateResponse
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    # admin views
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'', include('users.urls', namespace="users")),
    url(r'', include('posts.urls')),
]

if settings.DEBUG:
    urlpatterns +=  patterns('', (r'^404/$', TemplateResponse, {'template': '404.html'})) + \
                    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
                    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('users.views',

    url(r'^login/$', 'login_view', name='login'),
    url(r'^register/$', 'register_view', name='register'),
    url(r'^logout/$', 'logout_view', name='logout'),
    
    url(r'^u/(?P<username>[-\w]+)/$', 'profile', name='profile'),
    url(r'^u/(?P<username>[-\w]+)/inbox/$', 'inbox', name='inbox'),
    url(r'^u/(?P<username>[-\w]+)/inbox/unread/$', 'unread', name='unread'),
    url(r'^u/(?P<username>[-\w]+)/upvoted/$', 'upvoted', name='upvoted'),
    url(r'^u/(?P<username>[-\w]+)/downvoted/$', 'downvoted', name='downvoted'),
)

posts/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from sorl.thumbnail import ImageField
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError
from users.models import Subscription, Inbox
from django.template import loader, Context
import itertools


post_full_template = loader.get_template("includes/post.html")
post_html_template = loader.get_template("includes/post_html.html")

class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True)

    class Meta:
        ordering = ("title",)
        
    def __unicode__(self):
        return "%s" % (self.title)
    
    def get_absolute_url(self):
        return reverse('category', args=[self.slug])
    
class Tag(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True)

    class Meta:
        ordering = ("title",)
    
class Post(models.Model):
    title = models.CharField(max_length=500, null=True, blank=True)
    slug = models.SlugField(max_length=500, unique=True, null=True, blank=True)
    text = models.TextField(null=True, blank=True)
    url = models.URLField(max_length=500, null=True, blank=True)
    category = models.ForeignKey(Category)
    thumb = ImageField(upload_to="thumbs", null=True, blank=True)
    user = models.ForeignKey(User, null=True, blank=True)
    credit = models.IntegerField(default=0)
    tags = models.ManyToManyField(Tag, blank=True)
    parent = models.ForeignKey("self", null=True, blank=True, related_name="children")
    first_parent = models.ForeignKey("self", null=True, blank=True, related_name="all_children")
    created_date = models.DateTimeField(auto_now_add=True)
    subscribers = models.ManyToManyField(User, through='users.Subscription', related_name='subscribed')
    edit_count = models.IntegerField(default=0)
    
    class Meta:
        ordering = ("-credit", "-created_date",)
        
    def __unicode__(self):
        return "%s" % (self.title if self.title else self.text[:20])

    def html(self, user=None):
        return post_html_template.render({
            'post': self,
            'user': user
        })

    def full_html(self, user=None):
        return post_full_template.render({
            'post': self,
            'user': user
        })
    
    def get_first_parent(self):
        if self.parent:
            return self.parent.get_first_parent()
        return self
    
    def give_credit(self, credit):
        self.credit += credit
        self.save(compute_credit=False)
        
    def compute_credit(self, save=True):
        credits = self.credit_set.all()
        self.credit = 0
        if credits:
            self.credit = credits.aggregate(models.Sum("amount"))["amount__sum"]
        if save: self.save(compute_credit=False)
    
    def get_url(self):
        return self.url if self.url else self.get_absolute_url()
    
    def get_absolute_url(self):
        return reverse('post', args=[self.category.slug, self.slug])

    def clean(self):
        if self.parent == self:
            raise ValidationError("Circular relationship with parent")
        if not self.url and not self.text:
            raise ValidationError("Enter a url or description.")
    
    def get_unique_slug(self, to_slug):
        slug = slugify(to_slug)
        for x in itertools.count(1):
            if not Post.objects.filter(slug=slug).exists():
                break
            slug = '%s-%d' %(to_slug, x)
        return slug
    
    def save(self, compute_credit=True):
        if not self.id:
            parent = self.get_first_parent()
            self.category = parent.category
            try:
                self.first_parent = parent
            except ValueError:
                self.first_parent = None
                
            if not self.slug:
                self.slug = self.get_unique_slug(self.title or self.text[:50])
        if compute_credit:
            self.compute_credit(save=False)
        
        super(Post, self).save()
    
class Hit(models.Model):
    user = models.ForeignKey(User)
    post = models.ForeignKey(Post)
    created_date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ("-created_date",)
            
    def __unicode__(self):
        return "%s - %s" % (self.user, self.post)
    
class CreditManager(models.Manager):
    def upvotes(self, *args, **kwargs):
        return self.get_queryset().filter(**kwargs).filter(amount=1)
    def downvotes(self, *args, **kwargs):
        return self.get_queryset().filter(**kwargs).filter(amount=-1)
    
class Credit(models.Model):
    user = models.ForeignKey(User)
    post = models.ForeignKey(Post, related_name="credit_set")
    amount = models.IntegerField(default=0)
    created_date = models.DateTimeField(auto_now=True)
    objects = CreditManager()
    
    class Meta:
        ordering = ("-created_date",)
        unique_together = (("user", "post"))
        
    def __unicode__(self):
        return "%s - %s - %s" % (self.user, self.post, self.credit)
    
    def credit(self, amount=1):
        self.post.give_credit(-self.amount+amount)
        if self.post.user:
            self.post.user.profile.give_credit(-self.amount+amount)
        self.amount = amount
        self.save()
    
    def accredit(self):
        self.credit()
    
    def discredit(self):
        self.credit(amount=-1)
    
    def save(self, *args, **kwargs):
        super(Credit, self).save(*args, **kwargs)
    
    def delete(self, *args, **kwargs):
        self.post.give_credit(-self.amount)
        if self.post.user:
            self.post.user.profile.give_credit(-self.amount)
        super(Credit, self).delete(*args, **kwargs)
    

posts/forms.py
from django.forms import ModelForm
from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ["title", "url", "text", "category"]

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields["title"].required = True
    

posts/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from utils import redirect
from utils.breadcrumbs import *
from utils.paginate import get_paginated
from .models import *
from .forms import *


def home(request):
    posts = Post.objects.filter(parent__isnull=True)
    context = {
        'posts': get_paginated(request, posts),
        'breadcrumbs': home_breadcrumbs(),
    }
    return render_to_response("posts/home.html", context, context_instance = RequestContext(request))

def category(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    posts = Post.objects.filter(parent__isnull=True, category=category)
    context = {
        'posts': get_paginated(request, posts),
        'category': category,
        'breadcrumbs': category_breadcrumbs(category),
    }
    return render_to_response("posts/category.html", context, context_instance = RequestContext(request))

@csrf_exempt
def post(request, category_slug, post_slug):
    post = get_object_or_404(Post, slug=post_slug, category__slug=category_slug)
    
    if request.POST:
        if request.user.is_anonymous():
            raise PermissionDenied # Redirect to login
        
        if request.POST["text"]:
            reply = Post(text=request.POST["text"], user=request.user, parent=post)
            reply.save()
            return redirect(request)
            
    context = {
        'post': post,
        'category': post.category,
        'breadcrumbs': post_breadcrumbs(post),
    }
    return render_to_response("posts/post.html", context, context_instance = RequestContext(request))

@csrf_exempt
def edit(request, category_slug, post_slug):
    post = get_object_or_404(Post, slug=post_slug, category__slug=category_slug)

    if request.user.is_anonymous() or request.user != post.user:
        raise PermissionDenied # Redirect to login
        
    if request.POST:
        post.text = request.POST["text"]
        post.edit_count += 1
        post.save()
        return redirect(request)
            
    context = {
        'post': post,
        'category': post.category,
        'next': request.META['HTTP_REFERER'],
        'breadcrumbs': post_edit_breadcrumbs(post),
    }
    return render_to_response("posts/edit.html", context, context_instance = RequestContext(request))

@csrf_exempt
def delete(request, category_slug, post_slug):
    post = get_object_or_404(Post, slug=post_slug, category__slug=category_slug)

    if request.user.is_anonymous() or request.user != post.user:
        raise PermissionDenied # Redirect to login
        
    if request.POST:
        if not post.children.all() and request.POST["make_anonymous"] == "0":
            post.delete()
        else:
            post.user = None
            post.save()
        return redirect(request)
            
    context = {
        'post': post,
        'category': post.category,
        'next': request.META['HTTP_REFERER'],
        'breadcrumbs': post_edit_breadcrumbs(post),
    }
    return render_to_response("posts/delete.html", context, context_instance = RequestContext(request))

def credits(request, category_slug, post_slug):
    post = get_object_or_404(Post, slug=post_slug, category__slug=category_slug)
    context = {
        'post': post,
        'category': post.category,
        'upvotes': Credit.objects.upvotes(post=post),
        'downvotes': Credit.objects.downvotes(post=post),
        'breadcrumbs': post_credits_breadcrumbs(post)
    }
    return render_to_response("posts/credits.html", context, context_instance = RequestContext(request))

@login_required
def upvote(request, category_slug, post_slug):
    print post_slug, category_slug
    post = get_object_or_404(Post, slug=post_slug, category__slug=category_slug)
    credit, created = Credit.objects.get_or_create(user=request.user, post=post)
    if created:
        credit.accredit()
    else:
        if credit.amount < 0:
            credit.accredit()
        else:
            credit.delete()
    return redirect(request)

@login_required
def downvote(request, category_slug, post_slug):
    post = get_object_or_404(Post, slug=post_slug, category__slug=category_slug)
    credit, created = Credit.objects.get_or_create(user=request.user, post=post)
    if created:
        credit.discredit()
    else:
        if credit.amount > 0:
            credit.discredit()
        else:
            credit.delete()
    return redirect(request)

@login_required
def new(request, category_slug=None):
    category = Category.objects.filter(slug=category_slug).first()
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect(request, url=reverse("post", args=[post.category.slug, post.slug]))
    else:
        form = PostForm(initial={'category': category})
    context = {
        'form': form,
        'category': category
    }
    return render_to_response("posts/new.html", context, context_instance = RequestContext(request))

@login_required
def subscribe(request, category_slug, post_slug):
    post = get_object_or_404(Post, slug=post_slug, category__slug=category_slug)
    if not post.subscribers.filter(username=request.user.username).exists():
        Subscription(post=post, user=request.user).save()
    return redirect(request)

@login_required
def unsubscribe(request, category_slug, post_slug):
    post = get_object_or_404(Post, slug=post_slug, category__slug=category_slug)
    exists = Subscription.objects.filter(post=post, user=request.user).first()
    if exists:
        exists.delete()
    return redirect(request)

templates/includes/breadcrumbs.html
<ol class="breadcrumb">
    {% for crumb in breadcrumbs %}
    <li {% if crumb.active %}class="active"{% endif %}><a href="{{ crumb.url }}">{{ crumb.text }}</a></li>
    {% endfor %}
</ol>

templates/includes/post-info.html
{% load post_helper %}

<div class="info">by {% if post.user %}<a href="{{ post.user.profile.get_absolute_url }}">{{ post.user }}</a>{% else %}anonymous{% endif %} {{ post.created_date|timesince }} ago in <a href="{{ post.category.get_absolute_url }}">{{ post.category }}</a></div>
<a href="{% url 'credits' post.category.slug post.slug %}">{{ post.credit }}</a>
<a href="{% url 'upvote' post.category.slug post.slug %}?next={{ next }}">
    {% if post|has_upvoted:user %}Unupvote{% else %}Upvote{% endif %}
</a>
<a href="{% url 'downvote' post.category.slug post.slug %}?next={{ next }}">
    {% if post|has_downvoted:user %}Undownvote{% else %}Downvote{% endif %}
</a>
{% if post.user == user %}
    <a href="{% url 'edit' post.category.slug post.slug %}">Edit</a>
    <a href="{% url 'delete' post.category.slug post.slug %}">Delete</a>
{% endif %}
<a href="{% url 'post' post.category.slug post.slug %}">Permalink</a>
{% if post|is_subscribed:user %}
    <a href="{% url 'unsubscribe' post.category.slug post.slug %}?next={{ next }}">Unsubscribe</a>
    {% if js %}
        <script type="text/javascript">
            subscribed.push({{ post.id }});
        </script>
    {% endif %}
{% else %}
    <a href="{% url 'subscribe' post.category.slug post.slug %}?next={{ next }}">Subscribe</a>
{% endif %}
{% if main and post.parent %}<a href="{% url 'post' post.parent.category.slug post.parent.slug %}">Parent</a>{% endif %}
<a class="reply" href="javascript:document.getElementById('reply-{{ post.id }}').style.display='block'; void(0);">Reply</a>

templates/includes/post.html
<div class="post">
    {% include "includes/post_html.html" %}
    
    {% if post.children %}
    <ul class="children">
        {% for post in post.children.all %}
            <li class="post_li">
                {% include "includes/post.html" with post=post main=False %}
            </li>
        {% endfor %}
    </ul>
    {% endif %}
</div>

templates/includes/post_html.html
{% load markdown_deux_tags %}

<article id="{{ post.id }}">
    {% if main %}<h1><a href="{{ post.get_absolute_url }}">{{ post }}</a></h1>{% endif %}
    <p>
        {% if post.url %}<a href="{{ post.url }}">{{ post.url }}</a>{% endif %}
        {{ post.text|markdown }}
    </p>
    <div class="options">
        {% include "includes/post-info.html" %}
    </div>

    <form id="reply-{{ post.id }}" {% if main %}class="always_show"{% else %}style="display: none"{% endif %} method="post" action="{{ post.get_absolute_url }}">
        <input type="hidden" name="next" value="{{ main_post.get_absolute_url }}" />
        <textarea name="text" rows="3" cols="60"></textarea><br/>
        <input type="submit" value="Submit" />
    </form>

</article>

templates/includes/user-nav.html
<li>
    <a href="{% url "users:profile" this_user.username %}">{% if user == this_user %}Profile{% else %}{{ this_user.username }}{% endif %}</a>
    <ul>
        {% if user == this_user %}
        <li>
            <a href="{% url "users:inbox" this_user.username %}">Inbox</a>
            <ul>
                <li><a href="{% url "users:unread" this_user.username %}">Unread</a></li>
            </ul>
        </li>
        {% endif %}
        <li><a href="{% url "users:upvoted" this_user.username %}">Upvoted</a></li>
        <li><a href="{% url "users:downvoted" this_user.username %}">Downvoted</a></li>
        {% if user == this_user %}
        <li>
            <a href="{% url 'users:logout' %}">Logout</a>
        </li>
        {% endif %}
    </ul>
</li>

templates/includes/votes-list.html
<ul>
    {% for vote in votes %}
        <li><a href="{{ vote.user.profile.get_absolute_url }}">{{ vote.user.username }}</a> {{ vote.created_date|timesince }} ago</li>
    {% empty %}
        <li>Nobody {{ action }} this post.</li>
    {% endfor %}
</ul>