urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.template.response import TemplateResponse
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    # admin views
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'', include('users.urls', namespace="users")),
    url(r'', include('posts.urls')),
]

if settings.DEBUG:
    urlpatterns +=  patterns('', (r'^404/$', TemplateResponse, {'template': '404.html'})) + \
                    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
                    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('users.views',

    url(r'^login/$', 'login_view', name='login'),
    url(r'^register/$', 'register_view', name='register'),
    url(r'^logout/$', 'logout_view', name='logout'),
    
    url(r'^u/(?P<username>[-\w]+)/$', 'profile', name='profile'),
    url(r'^u/(?P<username>[-\w]+)/inbox/$', 'inbox', name='inbox'),
    url(r'^u/(?P<username>[-\w]+)/inbox/unread/$', 'unread', name='unread'),
    url(r'^u/(?P<username>[-\w]+)/upvoted/$', 'upvoted', name='upvoted'),
    url(r'^u/(?P<username>[-\w]+)/downvoted/$', 'downvoted', name='downvoted'),
)

templates/base.html
{% load staticfiles %}

<html>
    <head>
        <title>{{ SETTINGS.title }} - {% block title %}{{ SETTINGS.tagline }}{% endblock %}</title>
        {% block extra_head %}{% endblock %}
    </head>
    <body>
        {% block body %}
        <header>
            {% block header %}
                <h1><a href="{% url "home" %}">{{ SETTINGS.title }}</a></h1>
            {% endblock %}
        </header>
        <hr />
        <nav>
            {% include "includes/breadcrumbs.html" %}
        </nav>
        <hr />
        <section>
            {% block content %}
            {% endblock %}
        </section>
        <hr />
        <aside>
            <nav><ul>
                {% block nav %}{% endblock %}

                {% if user.is_anonymous %}
                    <li><a href="{% url "users:login" %}?next={{ request.path }}">Login</a></li>
                    <li><a href="{% url "users:register" %}?next={{ request.path }}">Register</a></li>
                {% else %}
                    {% include "includes/user-nav.html" with this_user=user %}
                {% endif %}

                <li>
                    {% if category %}<a href="{% url "new" category.slug %}">
                    {% else %}<a href="{% url "new" %}">{% endif %}Submit a new post</a>
                </li>

                <li>
                    <span>Categories</span>
                    <ul>
                        <li><a href="{% url "home" %}">All</a></li>
                        {% for category in categories %}
                        <li><a href="{{ category.get_absolute_url }}">{{ category }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            </ul></nav>
        </aside>
        <hr />
        <footer>
            {% block footer %}{% endblock %}
            <p>&copy; Creddit.co 2015. All rights reserved.</p>
        </footer>
        {% endblock %}
    </body>
</html>